### ISSUE TITLE
Duplicate entry in Notification Center upon fresh install

### ISSUE THREAD

**Issue by socketbox** [ungoogled-software/ungoogled-chromium-macos#85] opened 2021-12-09 00:50 UTC
Fresh installation of Ungoogled Chromium on macOS 12.1 beta. Notification Center shows two nearly identical entries (from user's standpoint). One has banner notifications enabled, the other Alerts.
<img width="605" alt="Screen Shot 2021-12-08 at 7 45 58 PM" src="https://user-images.githubusercontent.com/1593835/145314420-bdb3812a-0ac0-4d74-91d5-69af9473ed65.png">
<img width="618" alt="Screen Shot 2021-12-08 at 7 45 44 PM" src="https://user-images.githubusercontent.com/1593835/145314428-223fd4f3-f743-4778-a615-9b247a30992c.png">

**Comment by kramred** [comment] 2021-12-09 10:08
This might be caused by Chromium.app being present in (two) different locations.

Try running this in Terminal:

```bash
mdfind -name Chromium.app
```

If that only yields one location it might also be an Electron app where the Chromium.app is detected by macOS Notification service.

If you're using `brew` ([Homebrew](https://brew.sh) package manager) check in the [`HOMEBREW_PREFIX`](https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-opthomebrew-on-apple-silicon)  folder.

This will show you the `HOMEBREW_PREFIX`  folder
```bash
brew config
```

Then run something like this:

```bash
find /usr/local/ /opt/homebrew -name "Chrmium.app" 2>/dev/null 
```

Otherwise you could run find starting on `/` (with or without `sudo`)

```bash
sudo find / -name "Chrmium.app" 2>/dev/null 
```

**Comment by PF4Public** [comment] 2024-02-27 14:02
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Closed by PF4Public** 2024-02-27 14:02 UTC
